<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ProducerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $producers = [

            ['name' =>'Галичфарм, ПАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Кусум Фарм, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Кусум Хелтхкер ПВТ.ЛТД', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ФарКоС', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Киевский витаминный завод, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Технолог, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармак, ПАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Здоровье, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'НОБЕЛ ИЛАЧ САНАЙИ ВЕ ТИДЖАРЕТ А.Ш.', 'country'=>'Турция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ИнтерХим, ОДО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Опытный завод ГНЦЛС, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Дарница ФФ, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Киевмедпрепарат, ОАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Монфарм, ОАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Борщаговский ХФЗ, ЗАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Richard Bittner Pharma', 'country'=>'Австрия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Орисил-Фарм, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ФарКос', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармекс Групп, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Sopharma AD', 'country'=>'Болгария', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Доктор Герхард Манн, Химико ГмбХ', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармак, ПАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Делфарм Хюнинг сас', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Mepro Pharmaceuticals Pvt., Ltd', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Эйм НПФК, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармстандарт-Биолек, ПАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Сперко Украина, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Киевский витаминный завод, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Acino Pharma AG', 'country'=>'Швейцария', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармак, ПАО', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Menarini Group', 'country'=>'Италия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Nabros Pharma Pvt., Ltd', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Глаксо Оперэйшенс Великобритания Лимитед', 'country'=>'Великобритания', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Эйсика Фармасьютикалз ГмбХ ', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ООО “Микрофарм”', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ФАРМАСАЙНС ИНК.', 'country'=>'Канада', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Unimed Pharma s.r.o.', 'country'=>'Словакия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ЛУБНЫФАРМ, АО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ИГАР, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ФАРМЗАВОД ЕЛЬФА А.О. ', 'country'=>'Польша', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Актавис ЛTД', 'country'=>'Мальта', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Опытный завод ГНЦЛС, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фитофарм', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Евертоджен Лайф Саэнсиз Лiмiтед', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Berlin-Chemie AG', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'KRKA', 'country'=>'Словения', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'АйПиЭр Фармасьютикалс Инк.', 'country'=>'США', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фарма Старт, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Виола', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Астрафарм, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Житомирская фармацевтическая фабрика ДКП, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Тернофарм, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Феррер Интернасьональ С.А.', 'country'=>'Испания', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Merckle GmbH', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фамар А.В.Е', 'country'=>'Греция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'GlaxoSmithKline', 'country'=>'Ирландия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Здоровье, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Витамины, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Безен Мэньюфекчуринг Белджиум', 'country'=>'Бельгия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ЭкоФарм НПЦ, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'TROMMSDORFF GmbH & Co.KG', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Дойче Хомеопати-Унион -Арцнаймиттель ГмбХ & Ко.,', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'KRKA', 'country'=>'Словения', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Агрофарм, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Мерк Шарп и Доум', 'country'=>'Великобритания', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Georg BioSystems', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Валартин Фарма, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Житомирская фармацевтическая фабрика ДКП, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Иннотера Шузи', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ЭНГЕЛЬГАРД АРЦНАЙМИТТЕЛЬ ГМБХ', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Х.УРИАК И КОМПАНИЯ С.А', 'country'=>'Испания', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Артура Фармасьютикалз ПВТ.ЛТД', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фарма Интернешнл', 'country'=>'Иордания', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'SENTISS PHARMA, Pvt. Ltd.', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ЗЕНТИВА ', 'country'=>'Чехия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Креома-Фарм ЭОФ, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Лубныфарм, ПАО ', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Индар, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Лекхим, АО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Здоровье ХФ3, АО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Микрохим НПФ, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'СмитКляйн Бичем С.А.', 'country'=>'Испания', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Ананта Медикеар Лимитед', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Орисил-Фарм, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ФАРМАТИС С.А.С. ', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Биокон МНПО, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Неофлора, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Санека Фармасьютикалс а.с.', 'country'=>'Словакия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Юрия-Фарм', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Wuxi Hong Guang Medical Equipment ', 'country'=>' Китай', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Дарница ФФ, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Борщаговский ХФЗ, ЗАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Лубныфарм, ПАО ', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Richard Bittner', 'country'=>' Австрия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Агрофарм, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Красная звезда ОАО ', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Kusum Healthcare ', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Юник Фармасьютикал Лабораториз', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'АЛЬПИФЛОР С.Р.Л.', 'country'=>'Италия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'АЛЬПИФЛОР С.Р.Л.', 'country'=>'Италия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'КЕНДИ ЛТД', 'country'=>'Болгария', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Биосколь Ко.Лтд', 'country'=>'Израиль', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Биота, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ИННАТЕ С.Р.Л.', 'country'=>'Италия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'S.C. ZENTIVA', 'country'=>'Румыния', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Берингер Ингельхайм Эспана, С.А.', 'country'=>'Испания', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Байер Ваймар ГмбХ и Ко. КГ', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ТЕВА Фармацевтический завод', 'country'=>'Венгрия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ПВП Норма', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'GlaxoSmithKline Manufacturing', 'country'=>'Италия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ГЛЕНМАРК ФАРМАСЬЮТИКАЛЗ Лтд.', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Bayer AG', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ООО Исток плюс', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Новартис Консьюмер Хелс СА.', 'country'=>'Швейцария', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Алкон-Куврьор', 'country'=>'Бельгия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Биологише Хайльмиттель Хеель ГмбХ', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'МЕДОКЕМИ Лтд.', 'country'=>'Кипр', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'АВС Фармацойтичи С.п.А.', 'country'=>'Италия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Глаксо Веллком Продакшн', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'АО «Гриндекс»', 'country'=>'Латвия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Контракт Фармакал Корпорейшн', 'country'=>'США', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Шеринг-Плау', 'country'=>'Бельгия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'АО Сантен', 'country'=>'Финляндия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Пьер Фабр Медикамент Продакшн', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Bayer AG', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Мадаус ГмбХ', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Новофарм-Биосинтез, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Инфузия, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Лаборатории Сервье', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Санофи', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Sava Healthcare Limited', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Виво-Актив ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармекс Груп ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Дарница ФФ, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Неофлора ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Биота ООО Харьков', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ПрАТ "Інфузия"', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Лозен Фарма ПВТ.ЛТД.', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ЛекоПро, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Мукос Эмульсионс ГмбХ', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ФДС ЛТД', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Белмедпрепараты, РУП', 'country'=>'Белоруссия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Сандоз ГмбХ-ТехОпс', 'country'=>'Австрия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'МЕДИТОП ФАРМАСЬЮТИКАЛ ЛТД', 'country'=>'Венгрия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Лабораториос Алкала Фарма', 'country'=>'Испания', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'НСПС Хебей Хуамин Фармасьютикал Компани Лтд', 'country'=>'Китай', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Евро-плюс', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Новофарм-Биосинтез', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Медокеми ЛТД', 'country'=>'Кипр', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармекс', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'SANOFI WINTHROP INDUSTRIE', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Шенджен Текдоу Фармасьютикал Ко', 'country'=>'Китай', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'НВО Фитобиотехнологии', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Экобиз', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фито Доктор', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармаком', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Биофарма', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фарма Старт, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Селком', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Мибе ГмбХ Арцнаймиттель', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Санофи', 'country'=>'Италия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Профарма Плант', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Хиноин Завод Фармацевтических и Химических продуктов', 'country'=>'Венгрия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'MEDANA PHARMA', 'country'=>'Польша', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'KRKA', 'country'=>'Словения', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Ядран Галенский Лабораторий', 'country'=>'Хорватия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Хендок Инк.', 'country'=>'Корея', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Лаборатории Бушара-Рекордати', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'КУПЕР ЭС.ЭЙ', 'country'=>'Греция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Торрент Фармасьютикалс', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'СЕРВЬЕ ИНДАСТРИС ЛТД ', 'country'=>'Ирландия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Балканфарма-Разград', 'country'=>'Болгария', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'PLIVA HRVATSKA', 'country'=>'Хорватия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Балканфарма-Дупница', 'country'=>'Болгария', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Галичфарм, ПАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>' Лаборатории СЕРВЬЕ ИНДАСТРИС ЛТД ', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Медокеми ЛТД', 'country'=>'Кипр', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Русан Фарма', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Jiangsu Yuyue Med.Instrument Co', 'country'=>'Китай', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Пфайзер Менюфекчуринг Дойчленд ГмбХ', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармекс Групп, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Цефак', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'FAREVA AMBOISE', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Азиенде Кимике Риуните Анжелини', 'country'=>'Италия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Sava Healthcare', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ЭВЕРТОДЖЕН ЛАЙФ САЕНСИЗ', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'МАРКСАНС ФАРМА', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Jiangsu Yuyue Med.Instrument Co', 'country'=>'Китай', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармаком ', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Аспен нотер дам де Бондее', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Юрия-Фарм', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Лаборатории Сервье Индастри', 'country'=>'Ирландия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ФарКос', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Байер Фарма АГ', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Пфайзер Менюфекчуринг Бельгия', 'country'=>'Бельгия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Опытный завод ГНЦЛС, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармина ЛТД', 'country'=>'Польша', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармекс Групп, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Мепро Фармасьютикалс', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Берингер Ингельхайм Эспана, С.А.', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Биофарма', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Санофи С.п.А', 'country'=>'Италия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Мерк Шарп и Доум', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Алпекс Фарма', 'country'=>'Швейцария', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Эрбис', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Merckle GmbH', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'GlaxoSmithKline Dangarvan', 'country'=>'Ирландия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ДКП Фармацевтическая фабрика', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Киевмедпрепарат, ОАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фарма Старт, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Bayer AG', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ИнтерХим, ОДО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Технолог, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Монфарм, ОАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Тернофарм, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармак', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Гнцлс', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Коперасьон Фармасьюитк Франсез', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Янссен-Силаг', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фитофарм', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Георг Биосистемы', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Гнцлс', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Пфайзер Меньюфекчуринг', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Здоровье, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ИнтерХим, ОДО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Тернофарм, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Киевмедпрепарат, ОАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Биомед ', 'country'=>'Польша', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Эрбис', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Биофарма', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Bayer', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Дарница ФФ, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Технолог, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Эйсика Фармасьютикалз ГмбХ ', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармак', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Лабораторио Рейг Хофре', 'country'=>'Испания', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Норма', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фарма Интернешнл', 'country'=>'Иордания', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Берлин Хеми', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Евертоджен Лайф Саэнсиз Лiмiтед', 'country'=>'Индия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармаселект Интернешнл', 'country'=>'Австрия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Агрофарм, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Гедеон Рихтер', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармекс Групп, ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Хеалплант Плюс', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармаком ВТФ', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Георг Биосистемы', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Гнцлс', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'МЕДИТОП ФАРМАСЬЮТИКАЛ ЛТД', 'country'=>'Венгрия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Алпекс Фарма', 'country'=>'Швейцария', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'НОБЕЛ ИЛАЧ САНАЙИ ВЕ ТИДЖАРЕТ А.Ш.', 'country'=>'Турция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Технолог, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Тернофарм', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармак', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Красная звезда ОАО ', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Галичфарм, ПАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Киевмедпрепарат, ОАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Галичфарм, ПАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Неофлора ООО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'НВО Фитобиотехнологии', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Галичфарм, ПАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Галичфарм, ПАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Новофарм-Биосинтез', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Юрия-Фарм', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Киевский витаминный завод, ЧАО', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Лек', 'country'=>'Словения', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'ГлаксоСмитКлян', 'country'=>'Польша', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Гедеон Рихтер', 'country'=>'Венгрия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фарма ІнитІнтернешнал', 'country'=>'Иордания', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Cooperation Pharmaceutique Francaise', 'country'=>'Франция', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Салютас Фарма', 'country'=>'Германия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Софаримекс Индустрия Кимика и Фармасеутика', 'country'=>'Португалия', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Фармахеми', 'country'=>'Нидерланды', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],
            ['name' =>'Альта Колор', 'country'=>'Украина', 'created_at' => Carbon::now(), 'updated_at' =>Carbon::now()],



        ];
        \DB::table('producers')->insert($producers);
    }
}
